######################################################################
# Automatically generated by qmake (3.0) Sun Feb 8 19:23:20 2015
######################################################################

QT += testlib

CONFIG += testlib
TEMPLATE = app
TARGET = FileSystem

# Input
HEADERS += cluster.h file.h filemanager.h value.h \

SOURCES += cluster.cpp \
           file.cpp \
           filemanager.cpp \
           main.cpp \
           value.cpp \
