######################################################################
# Automatically generated by qmake (3.0) Sun Feb 8 20:30:48 2015
######################################################################

QT += testlib
INCLUDEPATH += ../FileSystem
TEMPLATE = app
TARGET = tests
INCLUDEPATH += .

# Input
HEADERS += tst_filemanager.h tst_file.h ../FileSystem/filemanager.h ../FileSystem/value.h ../FileSystem/cluster.h ../FileSystem/file.h\	

SOURCES += testRunner.cpp tst_filemanager.cpp tst_file.cpp \
	   ../FileSystem/filemanager.cpp \
           ../FileSystem/value.cpp \
           ../FileSystem/cluster.cpp \
	   ../FileSystem/file.cpp \
